### ISSUE TITLE
What is the bed file that is being referenced?

### ISSUE THREAD

**Issue by carbocation** [tf2/CNest#10]
In the [Usage Documentation](https://github.com/tf2/CNest/blob/master/src/example_cnest_py.md#run-step1-1) there is a comment about the index.bed file needing to have the same chromosome names as the BAM/CRAM file. Perhaps I just missed it, but what are the intended contents of the index.bed file?

**Comment by tf2** [comment]
Good question! And apologies for lack of documentation about this - we will
try to make it clearer.

This largely depends on your input data type (i.e. WES vs. WGS) and
desired/possible resolution.
- its important how you define these regions

For WGS - i would suggest 1Kb regions across the genome (non overlapping).
- you can find an example file here:
https://github.com/smshuai/CNest-nf/tree/main/data

For WES - it's interesting to consider....

A number of ways of trying to find the "optimum" regions across the targets
- relating to the resolution you might want and the efficiently of capture
for individual baits.
- best is probably to assess this upfront i.e. look at the coverage
profiles for the target regions and decide

But it would not be bad to simply go with e.g. target regions plus and
minus 200bp.

What is your data type?

**Comment by carbocation** [comment]
Thanks, that's very helpful! In my case, at least for a first pass, this is WES data in ~10k people.
