### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by smshuai** [tf2/CNest#2]
1. `Dockerfile` asked for several .txt files that do not exist. Right now using empty files to build.
```dockerfile
COPY src/index.txt /resources
COPY src/index_tab.txt /resources
COPY src/txt_covered_all_coverage.txt /resources
COPY src/QC_gender_example.txt /resources
```

2. To avoid segmentation error at step2
- BAM file needs to be indexed.
- index.txt needs matched chromosome names as BAM.

**Comment by tf2** [comment]
cool, I've updated the main branch to include blank files - hopefully that solves this issue.

we may want to add an automatic check on the BAM files for the index file at some point...
